# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cde4bf1796bea795757d642c139e8b2ba7665e7ad01c392ed50069daf06afb1dd4f59ef38fcf15336d5e3053eeb010a27e157c054951b9517d9848bec5c5c470

test:
  secret_key_base: 9ca9f2def9c11f5414dc6cbbc1f2484ea0edbebdc5377c9c81d4c43edc62f0cfb446dbd15c6f60761b45fa492f29251f751bb36ddf311b49d6a4ef7f6b70e6c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
